### ISSUE TITLE
Decide on a license type

### ISSUE THREAD

**Issue by eddieyu1998** [glimpse-protocol/common#3]
# Description

We should decide a license type for this common repo

# Acceptance Criteria

A license is chosen for this repo

# Todo

- [ ] investigate different types of license
- [ ] decide on one

# Options

## [GPL 3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

# Ref

https://tldrlegal.com/

**Comment by eddieyu1998** [comment]
It seems to me that the MIT license is the simplest and most straight forward one. Although I don't know if we'll have to do any additional things for the other dependencies that we use, and if the license matter in that case.

**Comment by samueldobbie** [comment]
Not sure if you're going with MIT / this can be closed?

**Comment by tim-hm** [comment]
It's been some time since I looked at licenses ... iirc there is a useful site that highlights the differences between the options. Anyone recall the site?

**Comment by mountEvarus** [comment]
> It's been some time since I looked at licenses ... iirc there is a useful site that highlights the differences between the options. Anyone recall the site?

Are you thinking of tldrlegal? Think Eddie has that in the refs of this issue

**Comment by tim-hm** [comment]
@almacgp do you have any thoughts on this for our frontend code? the tldr link in the desciption is useful

**Comment by almacgp** [comment]
If it's just front end, I am not sure I have an opinion. My only comment ... would this be determined by the open source code we are already using?

**Comment by tim-hm** [comment]
I think if we tried to go for a restrictive license then that would be problematic.

Ok lets go MIT @glimpse-protocol/frontend
